# Generated by Django 2.2.1 on 2019-05-04 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recol', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadImage',
            new_name='Upload',
        ),
    ]
