# Generated by Django 2.2.1 on 2019-05-04 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recol', '0002_auto_20190504_0411'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
